# Generated by Django 3.2.15 on 2023-03-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolioo', '0002_post_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
